SELECT SUM(FAKTURY.BRUTTO), FAKTURY.MOUTH, table1.name, table1.group, MIASTA.SIZE
FROM table1
INNER JOIN FAKTURY
ON FAKTURY.user_id = table1.id
INNER JOIN MIASTA
ON MIASTA.id = table1.city_id
WHERE FAKTURY.MOUTH = 'WRZESIEŃ'
GROUP BY table1.group
ORDER BY MIASTA.SIZE DESC