SELECT SUM(FAKTURY.BRUTTO), table1.name, table1.group, MIASTA.SIZE
FROM table1
INNER JOIN FAKTURY
ON FAKTURY.user_id = table1.id
INNER JOIN MIASTA
ON  MIASTA.id = table1.city_id
GROUP BY table1.group
ORDER BY
  CASE 
    WHEN MIASTA.SIZE = '>500' THEN 2
    WHEN MIASTA.SIZE = '<234' THEN 1
    WHEN MIASTA.SIZE = '>1000' THEN 3
  END
DESC